'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-eraco-black text-white">
      {/* Header */}
      <header className="border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-400 to-orange-600 flex items-center justify-center">
              <span className="text-white font-bold text-sm">E</span>
            </div>
            <span className="font-semibold text-lg">Eraco</span>
          </Link>
          <Link
            href="/"
            className="text-gray-400 hover:text-white transition-colors text-sm"
          >
            Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl font-bold mb-2">Terms and Conditions</h1>
          <p className="text-gray-400 mb-8">Effective Date: 4 April 2026</p>

          <div className="prose prose-invert prose-lg">
            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-300 leading-relaxed">
              By accessing or using Eraco, you agree to be bound by these Terms and Conditions. If you do not agree, you must discontinue use immediately.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Nature of the Service</h2>
            <p className="text-gray-300 leading-relaxed">
              Eraco is an AI-powered platform designed to assist users with various tasks. The service is provided on an "as-is" and "as-available" basis.
            </p>
            <p className="text-gray-300 leading-relaxed mt-4">
              Eraco operates using automated systems and artificial intelligence, which may produce incomplete, inaccurate, or unintended results.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">3. No Guarantees or Warranties</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              EracoAI makes no guarantees regarding:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>Accuracy, completeness, or reliability of outputs</li>
              <li>Fitness for a particular purpose</li>
              <li>Continuous, uninterrupted, or error-free operation</li>
            </ul>
            <p className="text-gray-300 leading-relaxed mt-4">
              All outputs generated by Eraco should be independently verified before being relied upon.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">4. User Responsibility</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              You acknowledge and agree that:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>You are solely responsible for how you use Eraco</li>
              <li>Any decisions, actions, or consequences resulting from the use of Eraco are your responsibility</li>
              <li>You will not rely on Eraco for critical, legal, financial, medical, or safety-related decisions without professional verification</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Limitation of Liability</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              To the maximum extent permitted by law, EracoAI shall not be liable for:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>Any direct, indirect, incidental, consequential, or special damages</li>
              <li>Loss of data, profits, business, or opportunities</li>
              <li>Errors, inaccuracies, or omissions in AI-generated outputs</li>
              <li>Any actions taken based on the use of Eraco</li>
            </ul>
            <p className="text-gray-300 leading-relaxed mt-4">
              Use of Eraco is entirely at your own risk.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">6. AI-Specific Disclaimer</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Eraco uses artificial intelligence models that:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>May generate incorrect, misleading, or incomplete information</li>
              <li>May not reflect real-world accuracy</li>
              <li>May produce outputs that are outdated or contextually incorrect</li>
            </ul>
            <p className="text-gray-300 leading-relaxed mt-4">
              AI-generated content is not a substitute for professional advice of any kind.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Privacy and Data Handling</h2>
            <p className="text-gray-300 leading-relaxed">
              Eraco is designed with a minimal data-awareness architecture.
            </p>
            <ul className="space-y-2 text-gray-300 mt-4">
              <li>Most processing occurs locally on your device</li>
              <li>EracoAI does not access or store your content</li>
              <li>Systems are limited to observing resource usage and system performance</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Acceptable Use</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              You agree not to use Eraco:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>For any illegal, harmful, or abusive activity</li>
              <li>To violate rights of others</li>
              <li>To attempt to reverse engineer, exploit, or disrupt the service</li>
              <li>In any way that may harm EracoAI, its infrastructure, or other users</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">9. Service Availability</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              EracoAI reserves the right to:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>Modify, suspend, or discontinue the service at any time</li>
              <li>Update or remove features without notice</li>
              <li>Restrict or terminate access in cases of misuse</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Indemnification</h2>
            <p className="text-gray-300 leading-relaxed">
              You agree to indemnify, defend, and hold harmless EracoAI from and against any claims, damages, liabilities, losses, and expenses arising out of:
            </p>
            <ul className="space-y-2 text-gray-300 mt-4">
              <li>Your use or misuse of Eraco</li>
              <li>Your violation of these Terms</li>
              <li>Any reliance on AI-generated outputs</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Intellectual Property</h2>
            <p className="text-gray-300 leading-relaxed">
              All rights, title, and interest in Eraco, including software, design, branding, and underlying technology, remain the exclusive property of EracoAI.
            </p>
            <p className="text-gray-300 leading-relaxed mt-4">
              Unauthorized use, reproduction, or distribution is strictly prohibited.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">12. Changes to Terms</h2>
            <p className="text-gray-300 leading-relaxed">
              EracoAI may update these Terms at any time. Continued use of Eraco after changes constitutes acceptance of the revised Terms.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">13. Governing Law and Jurisdiction</h2>
            <p className="text-gray-300 leading-relaxed">
              These Terms shall be governed by and interpreted in accordance with the laws of India.
            </p>
            <p className="text-gray-300 leading-relaxed mt-4">
              Any disputes arising out of or relating to these Terms or the use of Eraco shall be subject to the exclusive jurisdiction of the courts located in India.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">14. Arbitration Agreement</h2>
            <p className="text-gray-300 leading-relaxed">
              Any dispute, claim, or controversy arising out of or relating to these Terms or the use of Eraco shall be resolved through binding arbitration.
            </p>
            <ul className="space-y-2 text-gray-300 mt-4">
              <li>Arbitration shall be conducted in India</li>
              <li>The proceedings shall be conducted in English</li>
              <li>The decision of the arbitrator shall be final and binding</li>
            </ul>
            <p className="text-gray-300 leading-relaxed mt-4">
              You agree to waive the right to resolve disputes in court, except where prohibited by law.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">15. Class Action Waiver</h2>
            <p className="text-gray-300 leading-relaxed">
              You agree that any claims or disputes will be brought solely in your individual capacity and not as part of any class action, collective action, or representative proceeding.
            </p>
            <p className="text-gray-300 leading-relaxed mt-4">
              You waive any right to participate in class-action lawsuits against EracoAI.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">16. Contact</h2>
            <p className="text-gray-300 leading-relaxed">
              For any questions regarding these Terms, contact:{' '}
              <a href="mailto:eraco.ai.co@gmail.com" className="text-orange-400 hover:text-orange-300">
                eraco.ai.co@gmail.com
              </a>
            </p>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
}
